### ISSUE TITLE
World Gen Crash

### ISSUE THREAD

**Issue by alexgeek** [FireBall1725/Graves#53]
Crashed in the Nether due a NoClassDef error during world generation.
Using the latest Forge (1.10.2 - 12.18.1.2014).

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.40-beta.jar)
  IC2core (industrialcraft-2-2.6.1-ex110.jar)
  LoadingPlugin (Quark-beta-45.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 7/17/16 4:08 PM
Description: Exception ticking world

java.lang.NoClassDefFoundError: com/fireball1725/graves/client/render/TEGraveSR
    at com.fireball1725.graves.common.world.WorldGeneration.generate(WorldGeneration.java:34)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
    at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
    at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:974)
    at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
    at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
    at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.fireball1725.graves.client.render.TEGraveSR
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 13 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/IResourceManagerReloadListener
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 15 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.IResourceManagerReloadListener
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 19 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 21 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Server thread
Stacktrace:
    at com.fireball1725.graves.common.world.WorldGeneration.generate(WorldGeneration.java:34)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
    at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
    at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:974)
    at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
    at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
    at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221)

-- Affected level --
Details:
    Level name: world
    All players: 1 total; [EntityPlayerMP['perryperryperry'/577, l='world', x=-15.55, y=47.00, z=96.43]]
    Chunk stats: ServerChunkCache: 460 Drop: 0
    Level seed: -1435899099627912876
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 0 game time, 0 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Linux (amd64) version 3.16.0-23-generic
    Java Version: 1.8.0_45-internal, Oracle Corporation
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 279480904 bytes (266 MB) / 913309696 bytes (871 MB) up to 922746880 bytes (880 MB)
    JVM Flags: 0 total; 
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP 9.32 Powered by Forge 12.18.1.2014 39 mods loaded, 39 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2014-universal.jar) 
    UCHIJAAAA   Forge{12.18.1.2014} [Minecraft Forge](forge-1.10.2-12.18.1.2014-universal.jar) 
    UCHIJAAAA   bagginses{2.4.2d} [Bagginses](Bagginses-1.10-3.0.2a.jar) 
    UCHIJAAAA   Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
    UCHIJAAAA   BiomesOPlenty{4.1.0.2049} [Biomes O' Plenty](BiomesOPlenty-1.9.4-4.1.0.2049-universal.jar) 
    UCHIJAAAA   ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.10-alpha-1.0.0.jar) 
    UCHIJAAAA   JEI{3.7.7.233} [Just Enough Items](jei_1.10.2-3.7.7.233.jar) 
    UCHIJAAAA   BloodMagic{1.9.4-2.0.2-50} [Blood Magic: Alchemical Wizardry](BloodMagic-1.9.4-2.0.2-50.jar) 
    UCHIJAAAA   Botania{r1.8-312} [Botania](Botania-unofficial.r1.8-312.jar) 
    UCHIJAAAA   Chameleon{1.9.4-2.1.6} [Chameleon](Chameleon-1.9.4-2.1.6.jar) 
    UCHIJAAAA   chisel{MC1.9.4-0.0.6.33} [Chisel](Chisel-MC1.9.4-0.0.6.33.jar) 
    UCHIJAAAA   chiselsandbits{11.5} [Chisels & Bits](chiselsandbits-11.5.jar) 
    UCHIJAAAA   ElecCore{1.5.292} [ElecCore](ElecCore-1.9.4-1.5.292.jar) 
    UCHIJAAAA   deepresonance{1.2.0beta35} [DeepResonance](deepresonance-1.9.4-1.2.0beta35.jar) 
    UCHIJAAAA   endercore{1.10.2-0.4.1.40-beta} [EnderCore](EnderCore-1.10.2-0.4.1.40-beta.jar) 
    UCHIJAAAA   Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UCHIJAAAA   EnderIO{1.10.2-3.0.1.70_beta} [Ender IO](EnderIO-1.10.2-3.0.1.70_beta.jar) 
    UCHIJAAAA   EnderZoo{1.10-1.2.3.43} [Ender Zoo](EnderZoo-1.10-1.2.3.43.jar) 
    UCHIJAAAA   fastleafdecay{v10} [Fast Leaf Decay](FastLeafDecay-v10.jar) 
    UCHIJAAAA   IC2{2.6.1-ex110} [IndustrialCraft 2](industrialcraft-2-2.6.1-ex110.jar) 
    UCHIJAAAA   forestry{5.1.12.200} [Forestry](forestry_1.10.2-5.1.12.200.jar) 
    UCHIJAAAA   ftbl{2.1.0} [FTBLib](FTBLib-1.9.4-2.1.0-pre2.jar) 
    UCHIJAAAA   ftbu{2.1.0} [FTBUtilities](FTBUtilities-1.9.4-2.1.0-pre2.jar) 
    UCHIJAAAA   graves{1.10.2-b22-universal} [Graves Mod](graves-1.10.2-b22-universal.jar) 
    UCHIJAAAA   inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks](InventoryTweaks-1.61-58.jar) 
    UCHIJAAAA   IronChest{7.0.7.795} [Iron Chest](ironchest-1.10.2-7.0.7.795.jar) 
    UCHIJAAAA   mantle{1.10-0.10.3.jenkins156} [Mantle](Mantle-1.10-0.10.3.jar) 
    UCHIJAAAA   OpenComputers{1.6.0.2-beta.4} [OpenComputers](OpenComputers-MC1.10-1.6.0.2-beta.4.jar) 
    UCHIJAAAA   Psi{r1.0-36} [Psi](Psi-r1.0-36.jar) 
    UCHIJAAAA   Quark{beta-45} [Quark](Quark-beta-45.jar) 
    UCHIJAAAA   xreliquary{1.10.2-1.3.2.423} [Reliquary](Reliquary-1.10.2-1.3.2.423.jar) 
    UCHIJAAAA   rftools{5.06} [RFTools](rftools-1.10-5.06.jar) 
    UCHIJAAAA   rftoolsdim{4.30beta46} [RFTools Dimensions](rftoolsdim-1.10-4.30beta46.jar) 
    UCHIJAAAA   Roguelike{1.5.4} [Roguelike Dungeons](RoguelikeDungeons-1.10.2-1.5.4.jar) 
    UCHIJAAAA   roots{0.109} [Roots](roots-1.10.2-0.109.0.jar) 
    UCHIJAAAA   Signals{1.0} [Signals](Signals-1.9.4-0.4.1-universal.jar) 
    UCHIJAAAA   StorageDrawers{1.9.4-3.2.1} [Storage Drawers](StorageDrawers-1.9.4-3.2.1.jar) 
    UCHIJAAAA   tconstruct{1.10-2.3.3a.jenkins271} [Tinkers' Construct](TConstruct-1.10-2.3.3a.jar) 
    Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.10.2-0.4.1.40-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
IC2core (industrialcraft-2-2.6.1-ex110.jar)

LoadingPlugin (Quark-beta-45.jar)
  vazkii.quark.base.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)
        - WailaIntegration (Enabled/Not Forced)

```
EnderIO: No known problems detected.
Detailed RF API diagnostics:
              * RF API class 'EnergyStorage' is loaded from: jar:file:/home/perry/mc/1.10/mods/mcjtylib-1.10-1.9.8.jar!/cofh/api/energy/EnergyStorage.class
              * RF API class 'IEnergyConnection' is loaded from: jar:file:/home/perry/mc/1.10/mods/mcjtylib-1.10-1.9.8.jar!/cofh/api/energy/IEnergyConnection.class
              * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/home/perry/mc/1.10/mods/mcjtylib-1.10-1.9.8.jar!/cofh/api/energy/IEnergyContainerItem.class
              * RF API class 'IEnergyHandler' is loaded from: jar:file:/home/perry/mc/1.10/mods/mcjtylib-1.10-1.9.8.jar!/cofh/api/energy/IEnergyHandler.class
              * RF API class 'IEnergyProvider' is loaded from: jar:file:/home/perry/mc/1.10/mods/mcjtylib-1.10-1.9.8.jar!/cofh/api/energy/IEnergyProvider.class
              * RF API class 'IEnergyReceiver' is loaded from: jar:file:/home/perry/mc/1.10/mods/mcjtylib-1.10-1.9.8.jar!/cofh/api/energy/IEnergyReceiver.class
              * RF API class 'IEnergyStorage' is loaded from: jar:file:/home/perry/mc/1.10/mods/mcjtylib-1.10-1.9.8.jar!/cofh/api/energy/IEnergyStorage.class
              * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/home/perry/mc/1.10/mods/mcjtylib-1.10-1.9.8.jar!/cofh/api/energy/ItemEnergyContainer.class
              * RF API class 'TileEnergyHandler' is loaded from: jar:file:/home/perry/mc/1.10/mods/mcjtylib-1.10-1.9.8.jar!/cofh/api/energy/TileEnergyHandler.class
              * RF API class 'TileEnergyHandler' is loaded from: jar:file:/home/perry/mc/1.10/mods/mcjtylib-1.10-1.9.8.jar!/cofh/api/energy/TileEnergyHandler.class

Profiler Position: N/A (disabled)
Player Count: 1 / 20; [EntityPlayerMP['perryperryperry'/577, l='world', x=-15.55, y=47.00, z=96.43]]
Is Modded: Definitely; Server brand changed to 'fml,forge'
Type: Dedicated Server (map_server.txt)`
```

**Comment by nikkimas** [comment]
Got the same issue in the Overworld. The Player just ran around in the world and suddenly "Server Closed". Just because, here's the crash-report: [http://pastebin.com/f9VgptSa](http://pastebin.com/f9VgptSa)

**Comment by FusionLord** [comment]
This has been fixed in b24

**Comment by alexgeek** [comment]
Just tried the new version, can't get a full log at the moment as it didn't entirely crash the server but still can't log in.

`[16:29:16] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$PlayerTickEvent@6bd6c6e9:
java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
        at com.fireball1725.graves.common.event.Events.onPlayerTick(Events.java:202) ~[Events.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_258_Events_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:365) [FMLCommonHandler.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:382) [zs.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:292) [zs.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) [lu.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162) [me.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:212) [NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) [eo.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
`

**Comment by FusionLord** [comment]
Working on this one, Thank you for reporting.
